ADDON:ImportAPI(API_TYPE.LOCALE.id)
local language = X2Locale:GetLocale() or "en_us"
if language ~= "zh_cn" then
    SHOW = "Show"
    GR = "GR"
    CR = "CR"
    VOIDATTK = "Void"
    SGCR = "SG CR"
    JMG = "JMG"
    LUSCA = "Lusca"
    BD = "BD"
    KRAKEN = "Kraken"
    LEVIATHAN = "Leviathan"
    CHARYBDIS = "Charybdis"
    GANTHALON = "Anthalon G"
    HALCY = "Halcy"
    RD = "RD"
    ABYSSAL = "Abys atk"
    HASLA = "Hasla"
    AKASCH = "Akasch"
    PRAIRIE = "Prairie"
    WONDERLAND = "Wonderland Boss"
    INPROGTWOD = "Ends %02d min"
    INPROGONED = "Ends %d min"
    ONEDMIN = "%d min"
    TWODMIN = "%02d min"
    TWODHRTWODMIN = "%02dhr%02d min"
    TWODHRONEDMIN = "%02dhr%d min"
    ONEDHRONEDMIN = "%dhr%d min"
    ONEDHRTWODMIN = "%dhr%02d min"
    ONEDHR = "%dhr"
    TWODHR = "%02dhr"

    CRISIS = "Crisis"
    CONFLICT = "Conflict"
    WAR = "War"
    PEACE = "Peace"

    HOUR = "hr"
    MIN = "min"
    STATECN = ""

    PROGRASS = ""
    UNABLETOTRACK = "N/A"
    AEGIS = "AE"
    WH = "WH"
    YNYSWORD = "YNY"
    CINDERSWORD = "Cinder"
    GARDENBOSS = "Garden"
    WABOSS = "WA Spider"

    DRAGONFEST = "Dragon F"
    BSB = "BSB"
    NUI = "Nui"
    RESIDENT = "Resident"
    FISHPACK = "Lucky Coin"
    HIRAMONE = "T1"
    WHM = "WHM"
    EHM = "EHM"
    IPY = "Ipyna"
    GPW = "Prairie"

    EXP = "Exp:"
    GOLD = "Gold:"
    VOCATION = "Vocation:"
    HONOR = "Honor:"
    GSTRING = "g"

    NET_INCOME_TODY = "Net income"
    INFOADDON = "Info Addon"
    MAINPAGE = " Main Page"
    OTHERQUEST = "Other Quests"
    WEEKLY = "Weekly Quests"
    LIFE_DAILY = "Vocation Daily"

    CM_STATES = "Community Centers"
    MINI_SOF = "Mini SoF"
    GRAND_WORKBENCH = "Grand Workbench"
    SHIP_MERCHANT = "Ship Merchant"
    CAR_MERCHANT = "Car Merchant"
    ADV_PACKCRAFTOR = "Special Pack"

    NO_DATA = "No Data found"

    QUEST_INFO = "Quest Info"
    GNINFO = "General Info"
    NOBLESSING = "No Blessing"
    COS_EXPIRED = "Costume Expired"
    UND_EXPIRED = "Underwear Expired"
    NO_DAILY = "Daily unavailable"
    NO_UNLOCK_DAILY = "Daily locked"
    UNLOCKED_DAILY = "Daily unlocked"
    UNLOCKED_PART_DAILY = "Some daily locked"

    NO_GUILD_QUEST = "Guild quest locked"
    NO_GUILD_QUEST_UNLOCKED = "Guild quest locked"
    NO_GUILD = "User dont have guild"
    YES_GUILD = "Guild quest unlocked"
    PART_GUILD = "Part of guild quest locked"

    NO_WH_QUEST = "WH labor quest not found"
    NO_HALCY_QUEST = "Golden plain quest not found"

    COMPLETE = "Completed"
    INCOMPLETE = "Incomplete"

    SEARCHING = "Checking for "
    LESS_THAN_1G = "Less than 1g"
    NOSTAGETHREE = "No lv3 yet"

    WHBoss = "WH boss "
    CLOSEWIDGET = "Switch Widget"
    CLOSEDWIDGET = "Widget will be hidden untill next login or switch button"
    OPENEDWIDGET = "Widget will be Shown untill next login or switch button"

    NO_PACK_QUEST = "20 Pack Quest"
    NO_FISH_QUEST = "20 Fish Quest"

    RESETSTATS = "Reset"
else
    SHOW = "切换显示"
    GR = "迷雾"
    CR = "征兆"
    VOIDATTK = "虚空"
    SGCR = "征兆(原)"
    JMG = "JMG"
    LUSCA = "阿肯"
    BD = "黑龙"
    KRAKEN = "克拉肯"
    LEVIATHAN = "利维坦"
    CHARYBDIS = "卡迪利斯"
    GANTHALON = "庭院ATL"
    HALCY = "黄金"
    RD = "红龙"
    ABYSSAL = "深渊"
    HASLA = "翡翠"
    AKASCH = "守山"
    PRAIRIE = "大草原"
    WONDERLAND = "梦境"
    INPROGTWOD = "%02d分结束"
    INPROGONED = "%d分结束"
    ONEDMIN = "%d分开"
    TWODMIN = "%02d分"
    TWODHRTWODMIN = "%02d时%02d分"
    TWODHRONEDMIN = "%02d时%d分"
    ONEDHRONEDMIN = "%d时%d分"
    ONEDHRTWODMIN = "%d时%02d分"
    ONEDHR = "%d时"
    TWODHR = "%02d时"

    CRISIS = "危险"
    CONFLICT = "纷争"
    WAR = "战争"
    PEACE = "和平"

    HOUR = "时"
    MIN = "分"
    STATECN = "阶"

    PROGRASS = ""
    UNABLETOTRACK = "未知"
    AEGIS = "烛台"
    WH = "鲸鱼"
    YNYSWORD = "净化(东)"
    CINDERSWORD = "净化(西)"
    GARDENBOSS = "庭院"

    DRAGONFEST = "吸龙"
    BSB = "债券"
    NUI = "女神"
    RESIDENT = "住民"
    FISHPACK = "幸运币"
    HIRAMONE = "1阶段"
    WHM = "西部"
    EHM = "东部"
    IPY = "蛋山"
    GPW = "草原"
    WABOSS = "白雪Boss"

    EXP = "经验:"
    GOLD = "金币:"
    VOCATION = "生活点:"
    HONOR = "荣誉:"
    GSTRING = "金"
    LESS_THAN_1G = "小于1金"

    NET_INCOME_TODY = "今日净收入"
    INFOADDON = "信息插件"
    MAINPAGE = " 主页"
    OTHERQUEST = "其他每日"
    WEEKLY = "周常任务"
    LIFE_DAILY = "生活每日"

    CM_STATES = "住民阶段"
    MINI_SOF = "微弱繁荣"
    GRAND_WORKBENCH = "高级灿烂台"
    SHIP_MERCHANT = "限时船商"
    CAR_MERCHANT = "限时车商"
    ADV_PACKCRAFTOR = "特殊货物"

    NO_DATA = "无数据"

    QUEST_INFO = "任务信息"
    GNINFO = "角色信息"
    NOBLESSING = "未获得国王雕像Buff"
    COS_EXPIRED = "时装已过期"
    UND_EXPIRED = "内衣已过期"
    NO_DAILY = "每日不可用"
    NO_UNLOCK_DAILY = "每日未解锁"
    UNLOCKED_DAILY = "每日已解锁"
    UNLOCKED_PART_DAILY = "每日部分解锁"

    NO_GUILD_QUEST = "公会任务不可用"
    NO_GUILD_QUEST_UNLOCKED = "公会任务未解锁"
    NO_GUILD = "无公会"
    YES_GUILD = "已解锁公会任务"
    PART_GUILD = "部分公会任务"

    NO_WH_QUEST = "未领取鲸鱼豆奶任务"
    NO_HALCY_QUEST = "黄金战场币任务未领取"

    COMPLETE = "已完成"
    INCOMPLETE = "未完成"

    SEARCHING = "正在检测"
    NOSTAGETHREE = "未有3阶段"

    WHBoss = "鲸鱼boss"
    CLOSEWIDGET = "切换信息显示"
    CLOSEDWIDGET = "屏幕文字组件会在下次登录或切换前隐藏"
    OPENEDWIDGET = "屏幕文字组件会在下次登录或切换前显示"
    NO_PACK_QUEST = "20货任务未领取"
    NO_FISH_QUEST = "20鱼任务未领取"

    RESETSTATS = "重置"
end